services:
  - type: web
    name: dtcc-commentary-webapp
    env: python
    plan: free
    rootDir: dtcc-analysis-script
    buildCommand: pip install -r requirements_webapp.txt
    startCommand: python start_render.py
    envVars:
      - key: OPENAI_API_KEY
        sync: false
      - key: FLASK_ENV
        value: production
      - key: PORT
        value: 10000
    healthCheckPath: /
    autoDeploy: true
    branch: main